// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"githut.com/shaco-go/fiber-kit/core/server"
	"githut.com/shaco-go/fiber-kit/internal/handle"
	"githut.com/shaco-go/fiber-kit/internal/repo"
	"githut.com/shaco-go/fiber-kit/internal/router"
	"githut.com/shaco-go/fiber-kit/internal/service"
)

// Injectors from wire.go:

func NewWire() (*server.App, func(), error) {
	user := repo.NewUser()
	serviceUser := service.NewUser(user)
	handleUser := handle.NewUser(serviceUser)
	routerRouter := router.NewRouter(handleUser)
	httpServer := server.NewHttpServer(routerRouter)
	taskServer := server.NewTaskServer()
	app := newApp(httpServer, taskServer)
	return app, func() {
	}, nil
}

// wire.go:

func newApp(
	http *server.HttpServer,
	task *server.TaskServer,
) *server.App {
	return server.NewApp(server.WithServer(
		http,
		task,
	))
}
